-- SQL(Structure Query Language)
-- Divided into 4 sub-parts
--DDL(data defination language)
    --CREATE
    --DROP
    --ALTER
    --TRUNCATE
    --RENAME
--DML(Data Manipulation Language)
    --SELECT
    --INSERT
    --DELETE
    --UPDATE
--DCL(Data Control Language)
    --GRANT
    --REVOKE
--TCL(Transaction Control language)
    --COMMIT
    --ROLLBACK
    --SAVEBACK
    --SET TRANSACTION

--DDL examples:-
CREATE TABLE ep1 (ep_NAME VARCHAR(20), SURNAME VARCHAR2(10)); --CREATE TABLE
INSERT INTO ep2 VALUES ('MALAV', 'PATEL', 19);
DROP  TABLE ep2 ; --TO DELETE TABLE 
ALTER TABLE ep2 ADD  AGE NUMBER(10); --TO ADD COLUMN IN THE TABLE 
ALTER TABLE ep2 ADD  DEPT VARCHAR(30);
ALTER TABLE ep2 DROP COLUMN DEPT; 
TRUNCATE TABLE ep2; --TO DELETE ALL ROWS PRESENT IN THE TABLE
RENAME  ep1 to ep2; --TO RENAME THE TABLE
SELECT * FROM ep2;

--DML EXAMPLES 
CREATE TABLE STUDENTS (STNAME VARCHAR(30), SNAME VARCHAR(10), AGE INTEGER);
INSERT INTO STUDENTS VALUES ('AYUSH', 'CANADAWALA', '69'); --TO INSERT ROWS IN TABLE 
UPDATE STUDENTS SET  AGE = 21 WHERE STNAME = 'AYUSH'; --TO UPDATE VALUE IN THE TABLE 
DELETE FROM STUDENTS WHERE STNAME = 'AYUSH'; --DELETE ROWS IN THE DATABASE 
SELECT * FROM STUDENTS; --TO SELECT ALL ROWS IN THE TABLE AND DISLPAY 

--DCL COMMANDS 
GRANT SELECT, UPDATE ON STUDENTS TO DIP; --GRANT THE OPERATIONS TO ANOTHER USER
REVOKE SELECT, UPDATE ON STUDENTS FROM DIP;--REVOKE THE ACCESS FROM THE USER

--TCL EXAMPLES
COMMIT;
ROLLBACK;
SAVEPOINT;